---
- name: Disable rfkill
  ansible.builtin.copy:
    content: '0'
    dest: "/var/lib/systemd/rfkill/platform-{{ item }}.mmcnr:wlan"
  with_items:
    - 3f300000
    - fe300000

- name: Configure wpa_supplicant for country regulation
  ansible.builtin.lineinfile:
    regexp: '^country='
    line: "country={{ wifi_country }}"
    path: /etc/wpa_supplicant/wpa_supplicant.conf

- name: Enable cgroups v2 for containers
  ansible.builtin.lineinfile:
    regexp: '^(.*rootwait)'
    backrefs: true
    line: >
      \1 systemd.unified_cgroup_hierarchy=1
      cgroup_enable=cpuset
      cgroup_enable=memory cgroup_memory=1
    path: /boot/cmdline.txt
