---
version: 2

renderer: NetworkManager

ethernets:
  eth0:
    optional: true
    dhcp4: true
    dhcp6: true

## Static IP
#ethernets:
#  eth0:
#    dhcp4: false
#    dhcp6: false
#    addresses:
#      - 10.50.100.100/24
#    gateway: 10.50.100.1
#    nameservers:
#      search:
#        - home
#      addresses:
#        - 8.8.8.8
#        - 8.8.4.4

## WiFi
#wifis:
#  wlan0:
#    dhcp4: true
#    dhcp6: true
#    access-points:
#      "SSID":
#        password: "PASSWORD"

## WiFi AP
#wifis:
#  wlan0:
#    access-points:
#      "SSID":
#        mode: ap
#        password: "PASSWORD"
