#cloud-config

---
hostname: raspberry-0

manage_etc_hosts: true
timezone: America/Toronto
ssh_pwauth: false

users:
  ## Include "default" if you want default pi:raspberry user
  # - default
  - name: ansible
    gecos: Ansible provisioning user
    groups: sudo
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    ## Disable lock_passwd if you want to use this
    # passwd: ThisIsntStrongPassword
    lock_passwd: true
    # ssh_authorized_keys:
    #   - ssh-ed25519 ...
