---
name: Build modified RaspiOS images

on:
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [armhf, arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build image
        uses: ./.github/actions/build_image
        with:
          arch: ${{ matrix.arch }}
