---
name: Periodic build from upstream

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        required: true
        default: 'false'
        description: Force release
  schedule:
    - cron: 0 12 1 * *

jobs:
  check_upstream:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armhf, arm64]
    outputs:
      # https://github.community/t/bug-jobs-output-should-return-a-list-for-a-matrix-job/128626
      url_armhf: ${{ steps.out.outputs.url_armhf }}
      url_arm64: ${{ steps.out.outputs.url_arm64 }}
      sha256_armhf: ${{ steps.out.outputs.sha256_armhf }}
      sha256_arm64: ${{ steps.out.outputs.sha256_arm64 }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get latest RaspiOS release
        id: check
        uses: ./.github/actions/check_upstream
        with:
          arch: ${{ matrix.arch }}
      - name: Create outputs for matrix
        id: out
        run: |
          echo '::set-output name=url_${{ matrix.arch }}::${{ steps.check.outputs.url }}'
          echo '::set-output name=sha256_${{ matrix.arch }}::${{ steps.check.outputs.sha256 }}'

  update_vars:
    runs-on: ubuntu-latest
    needs: check_upstream
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate vars file
        run: |
          cat > rpi-cloudinit-image.auto.pkrvars.hcl <<EOF
          raspios_url = {
            armhf = "${{ needs.check_upstream.outputs.url_armhf }}"
            arm64 = "${{ needs.check_upstream.outputs.url_arm64 }}"
          }
          raspios_checksum = {
            armhf = "${{ needs.check_upstream.outputs.sha256_armhf }}"
            arm64 = "${{ needs.check_upstream.outputs.sha256_arm64 }}"
          }
          EOF

      - name: Update vars file
        id: update
        uses: EndBug/add-and-commit@v7.5.0
        with:
          default_author: github_actions
          message: Updated upstream RaspiOS version

      - name: Stop if not updated
        if: ${{ !(steps.update.outputs.pushed || github.event.inputs.force) }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Upstream version is not updated, no need to rebuild')

  build_image:
    runs-on: ubuntu-latest
    needs: update_vars
    strategy:
      matrix:
        arch: [armhf, arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - name: Build image and upload artifact
        uses: ./.github/actions/build_image
        with:
          arch: ${{ matrix.arch }}

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build_image
    steps:
      - name: Generate tag for release
        id: tag
        run: |
          date -u +"%Y-%m-%d" | xargs printf '::set-output name=tag::%s\n'

      - name: Download Artifacts
        id: download
        uses: actions/download-artifact@v2
        with:
          path: images/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            ${{steps.download.outputs.download-path}}/**/*.zip
            ${{steps.download.outputs.download-path}}/**/*.zip.sha256
          fail_on_unmatched_files: true
